src/Entity/FormEtat.php
<?php

namespace App\Entity;

use App\Repository\FormEtatRepository;
use App\Trait\DateTrait;
use App\Entity\Form;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FormEtatRepository::class)]
#[ORM\HasLifecycleCallbacks]
class FormEtat
{
    use DateTrait;
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $label = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $code_html = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $code_css = null;

    #[ORM\Column(type: Types::TEXT , nullable: true)]
    private ?string $code_compile_html = null;

    #[ORM\Column(type: Types::TEXT , nullable: true)]
    private ?string $codeCompileCss = null;

    #[ORM\ManyToOne(inversedBy: 'formEtats')]
    private ?Projet $projet = null;

    #[ORM\ManyToOne(inversedBy: 'formEtats')]
    private ?Form $form = null;

    #[ORM\OneToMany(mappedBy: 'formEtat', targetEntity: FormEtatVariable::class)]
    private Collection $formEtatVariables;

    public function __construct()
    {
        $this->formEtatVariables = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): static
    {
        $this->label = $label;

        return $this;
    }

    public function getCodeHtml(): ?string
    {
        return $this->code_html;
    }

    public function setCodeHtml(string $code_html): static
    {
        $this->code_html = $code_html;

        return $this;
    }

    public function getCodeCss(): ?string
    {
        return $this->code_css;
    }

    public function setCodeCss(string $code_css): static
    {
        $this->code_css = $code_css;

        return $this;
    }

    public function getCodeCompileHtml(): ?string
    {
        return $this->code_compile_html;
    }

    public function setCodeCompileHtml(?string $code_compile_html): static
    {
        $this->code_compile_html = $code_compile_html;

        return $this;
    }

    public function getCodeCompileCss(): ?string
    {
        return $this->codeCompileCss;
    }

    public function setCodeCompileCss(?string $codeCompileCss): static
    {
        $this->codeCompileCss = $codeCompileCss;

        return $this;
    }

    public function getProjet(): ?Projet
    {
        return $this->projet;
    }

    public function setProjet(?Projet $projet): static
    {
        $this->projet = $projet;

        return $this;
    }

    public function getForm(): ?Form
    {
        return $this->form;
    }

    public function setForm(?Form $form): static
    {
        $this->form = $form;

        return $this;
    }

    /**
     * @return Collection<int, FormEtatVariable>
     */
    public function getFormEtatVariables(): Collection
    {
        return $this->formEtatVariables;
    }

    public function addFormEtatVariable(FormEtatVariable $formEtatVariable): static
    {
        if (!$this->formEtatVariables->contains($formEtatVariable)) {
            $this->formEtatVariables->add($formEtatVariable);
            $formEtatVariable->setFormEtat($this);
        }

        return $this;
    }

    public function removeFormEtatVariable(FormEtatVariable $formEtatVariable): static
    {
        if ($this->formEtatVariables->removeElement($formEtatVariable)) {
            // set the owning side to null (unless already changed)
            if ($formEtatVariable->getFormEtat() === $this) {
                $formEtatVariable->setFormEtat(null);
            }
        }

        return $this;
    }
    public function __toString(){
        return $this->label;
    }
}

src/Form/FormEtatType.php
<?php

namespace App\Form;

use App\Entity\FormEtat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormEtatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('label')
            ->add('code_html')
            ->add('code_css')
            ->add('projet')
            ->add('form')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => FormEtat::class,
        ]);
    }
}

src/Controller/FormEtatController.php
<?php

namespace App\Controller;

use App\Entity\FormEtat;
use App\Entity\FormEtatVariable;
use App\Form\FormEtatType;
use App\Repository\FormEtatRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/form/etat')]
class FormEtatController extends AbstractController
{
    #[Route('/', name: 'app_form_etat_index', methods: ['GET'])]
    public function index(FormEtatRepository $formEtatRepository): Response
    {
        return $this->render('form_etat/index.html.twig', [
            'form_etats' => $formEtatRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_form_etat_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $formEtat = new FormEtat();
        $form = $this->createForm(FormEtatType::class, $formEtat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($formEtat);
            $entityManager->flush();

            return $this->redirectToRoute('app_form_etat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('form_etat/new.html.twig', [
            'form_etat' => $formEtat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_form_etat_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, FormEtat $formEtat, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FormEtatType::class, $formEtat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_form_etat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('form_etat/edit.html.twig', [
            'form_etat' => $formEtat,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_form_etat_delete', methods: ['GET'])]
    public function delete(Request $request, FormEtat $formEtat, EntityManagerInterface $entityManager): Response
    {
        $formEtatVariables = $entityManager->getRepository(FormEtatVariable::class)->findBy(['formEtat'=>$formEtat->getId()]);
        foreach ($formEtatVariables as $formEtatVariable){
            $entityManager->remove($formEtatVariable);
            $entityManager->flush();
        }
      //  if ($this->isCsrfTokenValid('delete'.$formEtat->getId(), $request->request->get('_token'))) {
            $entityManager->remove($formEtat);
            $entityManager->flush();
     //   }

        return $this->redirectToRoute('app_form_etat_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/form_etat/_delete_form.html.twig
<form method="post" action="{{ path('app_form_etat_delete', {'id': form_etat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ form_etat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/form_etat/_form.html.twig
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                {{ form_start(form) }}
                <div class="form-body">
                    <div class="row p-t-20">
                        <div class="col-md-6">
                            <div class="form-group">
                                {{ form_label(form.projet, 'Projet', {'label_attr': {'class': 'control-label'}}) }}
                                {{ form_widget(form.projet, {'attr': {'class': 'form-control', 'placeholder': 'Titre'}})
                                }}
                                {{ form_errors(form.projet) }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                {{ form_label(form.form, 'Formulaire', {'label_attr': {'class': 'control-label'}}) }}
                                {{ form_widget(form.form, {'attr': {'class': 'form-control', 'placeholder': 'Titre'}})
                                }}
                                {{ form_errors(form.form) }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                {{ form_label(form.label, 'label', {'label_attr': {'class': 'control-label'}}) }}
                                {{ form_widget(form.label, {'attr': {'class': 'form-control custom-select'}}) }}
                                {{ form_errors(form.label) }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                {{ form_label(form.code_html, 'code html', {'label_attr': {'class':
                                    'control-label'}}) }}
                                {{ form_widget(form.code_html, {'attr': {'class': 'textarea_editor form-control', 'placeholder':
                                    'Description Debut'}}) }}
                                {{ form_errors(form.code_html) }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                {{ form_label(form.code_css, 'code css', {'label_attr': {'class':
                                    'control-label'}}) }}
                                {{ form_widget(form.code_css, {'attr': {'class': 'textarea_editor2 form-control', 'placeholder':
                                    'Description Fin'}}) }}
                                {{ form_errors(form.code_css) }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-check"></i>
                        Save
                    </button>
                    <a href="" type="button" class="btn btn-inverse">Cancel</a>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
</div>

templates/form_etat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit FormEtat{% endblock %}

{% block body %}
    <h1>Edit FormEtat</h1>

    {{ include('form_etat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_form_etat_index') }}">back to list</a>

    {{ include('form_etat/_delete_form.html.twig') }}
{% endblock %}

templates/form_etat/index.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Expandable DataTable</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
</head>
<body>

<table id="myTable" class="display">
    <thead>
    <tr>
        <th></th>
        <th>ID</th>
        <th>Name</th>
        <th>Details</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td class="details-control"></td>
        <td>1</td>
        <td>Item 1</td>
        <td>Additional details for Item 1</td>
    </tr>
    <tr>
        <td class="details-control"></td>
        <td>2</td>
        <td>Item 2</td>
        <td>Additional details for Item 2</td>
    </tr>
    <!-- Add more rows as needed -->
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        var table = $('#myTable').DataTable({
            columnDefs: [{
                className: 'control',
                orderable: false,
                targets: 0
            }],
            order: [[1, 'asc']]
        });

        // Add event listener for opening and closing details
        $('#myTable tbody').on('click', 'td.details-control', function() {
            var tr = $(this).closest('tr');
            var row = table.row(tr);

            if (row.child.isShown()) {
                // This row is already open - close it
                row.child.hide();
                tr.removeClass('shown');
            } else {
                // Open this row
                row.child(format(row.data())).show();
                tr.addClass('shown');
            }
        });

        // Format details
        function format(data) {
            return '<div>Details: ' + data[3] + '</div>';
        }
    });
</script>

</body>
</html>

templates/form_etat/new.html.twig
<div class="modal fade" id="stepModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel1">Champs option</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="card">
                                        <div class="card-body">
                                            {# {{ form_start(form) }}
                                                                <div class="form-body">
                                                                    <div class="row p-t-20">
                                                                        <div class="col-md-6">
                                                                            <div class="form-group">
                                                                                {{ form_label(form.projet, 'Projet', {'label_attr': {'class': 'control-label'}}) }}
                                                                                {{ form_widget(form.projet, {'attr': {'class': 'form-control', 'placeholder': 'Titre'}})
                                                                                }}
                                                                                {{ form_errors(form.projet) }}
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-md-6">
                                                                            <div class="form-group">
                                                                                {{ form_label(form.form, 'Formulaire', {'label_attr': {'class': 'control-label'}}) }}
                                                                                {{ form_widget(form.form, {'attr': {'class': 'form-control', 'placeholder': 'Titre'}})
                                                                                }}
                                                                                {{ form_errors(form.form) }}
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-md-6">
                                                                            <div class="form-group">
                                                                                {{ form_label(form.label, 'label', {'label_attr': {'class': 'control-label'}}) }}
                                                                                {{ form_widget(form.label, {'attr': {'class': 'form-control custom-select'}}) }}
                                                                                {{ form_errors(form.label) }}
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    <div class="row">
                                                                        <div class="col-12">
                                                                            <div class="form-group">
                                                                                {{ form_label(form.code_html, 'code html', {'label_attr': {'class':
                                                                                    'control-label'}}) }}
                                                                                {{ form_widget(form.code_html, {'attr': {'class': 'textarea_editor form-control', 'placeholder':
                                                                                    'Description Debut'}}) }}
                                                                                {{ form_errors(form.code_html) }}
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    <div class="row">
                                                                        <div class="col-12">
                                                                            <div class="form-group">
                                                                                {{ form_label(form.code_css, 'code css', {'label_attr': {'class':
                                                                                    'control-label'}}) }}
                                                                                {{ form_widget(form.code_css, {'attr': {'class': 'textarea_editor2 form-control', 'placeholder':
                                                                                    'Description Fin'}}) }}
                                                                                {{ form_errors(form.code_css) }}
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="form-actions">
                                                                    <button type="submit" class="btn btn-success">
                                                                        <i class="fa fa-check"></i>
                                                                        Save
                                                                    </button>
                                                                    <a href="" type="button" class="btn btn-inverse">Cancel</a>
                                                                </div>
                                                                {{ form_end(form) }}#}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    {#                                        <a href="{{ path('app_form_etat_delete', {'id': form_etat.id}) }}" type="button" class="btn btn-red" id="elementActionButton">Supprimer</a>#}
                </div>
            </div>
        </div>
    </div>
</div>


    <script>
        $(document).ready(function() {
            // Basic
            $('.dropify').dropify();

            // Translated
            $('.dropify-fr').dropify({
                messages: {
                    default: 'Glissez-déposez un fichier ici ou cliquez',
                    replace: 'Glissez-déposez un fichier ou cliquez pour remplacer',
                    remove: 'Supprimer',
                    error: 'Désolé, le fichier trop volumineux'
                }
            });

            // Used events
            var drEvent = $('#input-file-events').dropify();

            drEvent.on('dropify.beforeClear', function(event, element) {
                return confirm("Do you really want to delete \"" + element.file.name + "\" ?");
            });

            drEvent.on('dropify.afterClear', function(event, element) {
                alert('File deleted');
            });

            drEvent.on('dropify.errors', function(event, element) {
                console.log('Has Errors');
            });

            var drDestroy = $('#input-file-to-destroy').dropify();
            drDestroy = drDestroy.data('dropify')
            $('#toggleDropify').on('click', function(e) {
                e.preventDefault();
                if (drDestroy.isDropified()) {
                    drDestroy.destroy();
                } else {
                    drDestroy.init();
                }
            })
        });
    </script>

    <script src="{{ asset('assets/plugins/dropify/dist/js/dropify.min.js') }}"></script>

    <script src="{{ asset('assets/plugins/html5-editor/wysihtml5-0.3.0.js') }}"></script>
    <script src="{{ asset('assets/plugins/html5-editor/bootstrap-wysihtml5.js') }}"></script>
    <script>
        $(document).ready(function() {

            $('.textarea_editor').wysihtml5();
            $('.textarea_editor2').wysihtml5();


        });
    </script>

{% endblock %}

templates/form_etat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}FormEtat{% endblock %}

{% block body %}
    <h1>FormEtat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ form_etat.id }}</td>
            </tr>
            <tr>
                <th>Label</th>
                <td>{{ form_etat.label }}</td>
            </tr>
            <tr>
                <th>Code_html</th>
                <td>{{ form_etat.codeHtml }}</td>
            </tr>
            <tr>
                <th>Code_css</th>
                <td>{{ form_etat.codeCss }}</td>
            </tr>
            <tr>
                <th>Code_compile_html</th>
                <td>{{ form_etat.codeCompileHtml }}</td>
            </tr>
            <tr>
                <th>CodeCompileCss</th>
                <td>{{ form_etat.codeCompileCss }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ form_etat.createdAt ? form_etat.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ form_etat.updatedAt ? form_etat.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_form_etat_index') }}">back to list</a>

    <a href="{{ path('app_form_etat_edit', {'id': form_etat.id}) }}">edit</a>

    {{ include('form_etat/_delete_form.html.twig') }}
{% endblock %}